<?xml version="1.0" encoding="utf-8"?><Database Name="GPSTracker" Class="GPSTrackerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KHUSHBU\SQLEXPRESS2;Initial Catalog=GPSTracker;User ID=sa" SettingsObjectName="GPSTrackerDal.Properties.Settings" SettingsPropertyName="GPSTrackerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usermap" Member="Usermaps">
    <Type Name="Usermap">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>